### ISSUE TITLE
Uploads all died on 14 May

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#136]
The archive.org feed of new/updated cases stopped updating on 14 May at 5:41pm (https://archive.org/services/collection-rss.php?collection=usfederalcourts). I emailed the archive and they said that the issue is not with the feed, there have been no new uploads since that time. I'm not familiar with the back end of recap, but it seems like uploads have broken somewhere along the line.

**Comment by mlissner** [comment]
Troubling. We didn't change anything I can think of, so something is probably up with the server. I'll take a look. Thanks for reporting this.

**Comment by mlissner** [comment]
Hi @jeffs000. I had a bunch of meetings today so this took some time before I could get it done. 

Ultimately, this was caused by a massive docket with thousands of entries that caused the script that pushes content to IA to get stuck. I'm not sure which specific docket caused the issue, but there are  dockets with something like 30,000 items, and they cause all kinds of headaches! 

There's a backlog on our server of things that people uploaded and these are pushing to IA now. You can expect it to flush out over the course of the next day or so. 

Thanks again for reporting this. Great to hear from our users.

**Comment by jeffs000** [comment]
Quick question -- the archive.org feed also gets stuck each day at about 12:30 UTC and doesn't update for 3-4 hours. Is that expected behavior of the recap servers?

**Comment by mlissner** [comment]
I assume you're talking about [this feed](https://archive.org/services/collection-rss.php?collection=usfederalcourts)? We don't see any regular issue with our uploads at 12:30 UTC. Could be an issue with the way RSS feeds are generated. 

Can you point me to where this is happening?

**Comment by jeffs000** [comment]
I presume it's the same feed, but I use https://archive.org/advancedsearch.php?q=collection%3Ausfederalcourts&fl[]=identifier&fl[]=publicdate&sort[]=addeddate+desc&sort[]=&sort[]=&rows=100&page=1&output=json#raw. It stops updating each day at about 12:30 UTC and today it restarted again at 15:30 UTC. This happens daily.

**Comment by mlissner** [comment]
This is likely an IA issue, so you might want to check with your contact there, but looking at the feed, I see entries between the times you mention. Is it that between 12:30 and 15:30, the feed didn't update, and then at 15:30, the feed suddenly showed all the items that had been updated during that time?

**Comment by jeffs000** [comment]
That's correct, the feed updates at about 15:30 to include all additions between 1230 and 1530, so the feed itself doesn't appear to have a gap.

**Comment by mlissner** [comment]
I see. Since this issue is closed (and about something else), can you open a fresh one with those details? I'll be happy to get in touch with our IA contact and see if we can get an official explanation once we have an issue where I can direct them.
