### ISSUE TITLE
Add a warning for users that Firefox doesn't work with history disabled

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#138]
A user has been having issues lately and they just figured out that the reason their RECAP extension doesn't work is because they have their history disabled.

I've seen a few extensions that will warn you when you have conflicting settings and that urge you to fix them. We should do this for RECAP, using the error triangle icon that we have to tell people to fix their configuration.

**Comment by mlissner** [comment]
Oddly, we never saw this before a week ago and now a second person has run into this. Curious.

**Comment by bkuhn** [comment]
I can confirm that I've seen an issue like this; I actually came to raise this as a new issue, but this existing one seems close.

I use private browsing mode, with a whitelist of exceptions first certain cookies (for which I've listed uscourts.gov pacer.gov and the like), but I still can't get Recap plugin to behave properly unless I turn off private browsing mode.  I didn't realize it might be related to the "Remember my browsing and download" history until reading this issue, but it makes sense.

A warning would be great, since the failure is confusing (Recap plugin just reports you aren't logged in).  Ideally, I'd love to see Recap work fine in private browsing mode, provided that you have the right cookies whitelisted.

**Comment by mlissner** [comment]
Yeah, Firefox must have changed something about the APIs we use. Good to know that private browsing is a part of the issue. Would be great to throw a warning if this problem is happening. If nothing else, we could try to detect it and make the icon red or something with a mouseover.

**Comment by mlissner** [comment]
This is worth revisiting to test if is fixed in the latest version of the extension.

**Comment by mlissner** [comment]
I just tried this in a private window in FF 57, and it worked fine. Private windows don't store history, so I think this is all good.
