### ISSUE TITLE
IA feed not updating properly

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#139]
Hello, it appears as though the Internet Archive feed of new and updated cases is severely under-reporting updates. 

https://archive.org/advancedsearch.php?q=collection%3Ausfederalcourts&fl[]=identifier&fl[]=publicdate&sort[]=addeddate+desc&sort[]=&sort[]=&rows=100&page=1&output=json#raw

Only a few cases a day have been added since 7/29, when normally it's hundreds.

**Comment by mlissner** [comment]
@jeffs000 you also filed #135. Is this distinct from that or can we combine these two issues? I have to say, I have no idea how the IA feed gets generated. It's something that's mostly out of our control, I believe.

**Comment by jeffs000** [comment]
These are distinct issues. I'm still having the problem in #135 where a case is updated through the recap plugin but doesn't show up on the IA feed. This issue is that the IA feed doesn't seem to be properly updating at all since 7/29.

As an alternative, is there another way of viewing recent recap uploads and new cases, besides the IA RSS feed?

**Comment by mlissner** [comment]
This is weird. The upload queue at IA is working perfectly fine (sometimes it gets clogged), so that's not it. I'm not aware of any better way to stay up to date, though we're planning a revamp of the entire system that should fix problems like this one. If all goes as planned, we'll be formally announcing that on Twitter/Email/Newsletter/blog fairly soon.

**Comment by mlissner** [comment]
This issue is over two years old and I'm not sure if it's resolved or obsolete or what. Closing, but please reopen if it's still valid.
