### ISSUE TITLE
Scraper not capturing all cases?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#141]
A comment from email:

> I noticed a little problem with RECAP today, and I'm sorry if this has
> been raised already.  I was downloading files for
> gov.uscourts.cacd.479401.\* and RECAP captured all the files with that
> pattern in the filename and put a notification on my screen, but the
> docket also contained a bunch of supplementary files with names like
> cacd-031010801177.pdf and so on.  RECAP didn't notify me that it had
> grabbed these ones and they don't seem to be in the Archive directory:
> 
> http://ia600306.us.archive.org/17/items/gov.uscourts.cacd.479401/

**Comment by brianwc** [comment]
Bug seems misnamed, it's docs not cases at issue. Follow-up email with more:

I have a little more information on this issue.  I said in my first
email that this has only to do with supplementary files (which don't
appear on the docket).  It turns out that some of the actual docketed
files have nonstandard names and also don't get captured by RECAP.  For
instance, here's the docket:

http://ia600306.us.archive.org/17/items/gov.uscourts.cacd.479401/gov.uscourts.cacd.479401.docket.html

Note that I downloaded item 22 from PACER a few hours ago.  The other
items I paid for at that time have shown up as links on the archived
version of the docket, but not this one.  The same thing is likely to
happen with item 7, which I just paid for a few minutes ago, but also
had the wrong name format.

**Comment by PlainSite** [comment]
I'm trying to capture data from the docket report and/or party pages for California Central Bankruptcy Court for Case No. 2:12-bk-26069-RK. No dice. I'm using Firefox 40.0.2 and RECAP 0.9.2.2.1.

**Comment by mlissner** [comment]
@PlainSite Are you using the Firefox or Chrome version? Also: Is this localized to this one case? Jurisdiction?

**Comment by PlainSite** [comment]
Firefox 40.0.2

**Comment by mlissner** [comment]
@PlainSite, you're too quick. Can you answer the other questions I tried to slip in before you answered?

**Comment by mlissner** [comment]
This is ancient. Not going to even try to figure out what the issue was here.
