### ISSUE TITLE
Case parties not updating

### ISSUE THREAD

**Issue by sammy447** [freelawproject/recap#144]
Hello,

I've tried re-updating the case below several times by re-uploading the docket and adding several PDFs, but for some reason the case's parties never show up in the docket html or xml files.

https://ia801000.us.archive.org/29/items/gov.uscourts.miwd.52979/

**Comment by mlissner** [comment]
The system currently has a very long backlog due to a huge docket that somebody uploaded. It's slowly flushing itself out, but it will take some more time to finish the job. Right now the queue has about 8,000 items, and it's currently processing about 1,000 every five hours. 

I wish we could fix this immediately, but there's no easy way. I'm going to close this issue since only time can fix it, but if it's still a problem in another few days, please do re-open it so we can investigate once the queue has been processed.

**Comment by sammy447** [comment]
Hello, this is still occurring. I've updated the case today. The docket files on the archive shows today's date, but the parties did not update.

**Comment by mlissner** [comment]
We'll take a look, but it could be a while, since we are very resource constrained.

**Comment by mlissner** [comment]
This is an old one that we never got to, and I'm happy to say that we are putting in all new infrastructure next week. If you haven't tried RECAP because of this bug, you might want to give it a try next week. I think things should be better.
