### ISSUE TITLE
dockets not showing up at archive.recapthelaw.org

### ISSUE THREAD

**Issue by ahessenflow** [freelawproject/recap#148]
Some dockets that have successfully made it to archive.org apparently have not shown up at archive.recapthelaw.org.  The ones I'm looking at are gov.uscourts.cand.286880 and gov.uscourts.cand.286881.  I tried the search engine at archive.recapthelaw.org in various ways and failed to find that case.  Thinking this might be a search indexing problem, I tried looking at other search results and deduce that the dockets should appear at archive.recapthelaw.org/cand/286880/ and 286881.  However both of those return page not found.

**Comment by mlissner** [comment]
Hi @ahessenflow. 

Unfortunately, archive.recapthelaw.org was a student project that we're no longer maintaining. 

Fortunately, we've gotten a matching grant to build a much more powerful version, and will be doing a fundraiser for the other half of the matching grant soon.

What this means for this issue is that:
1. We won't be looking into it in the near term (Sorry!), and 
2. We _will_ be building something much better in the next six months or so.

When the new system is built, it will have features like full text search, OCR, faceted search, etc.

I know this isn't the _best_ possible answer, but hopefully it makes sense. We do appreciate your getting in touch though. We're always happy to hear from our users (really!).
