### ISSUE TITLE
ContentDelegate.prototype.handleDocketQueryUrl never places docket banner on page

### ISSUE THREAD

**Issue by sjschultze** [freelawproject/recap#160]
https://github.com/freelawproject/recap-chrome/blob/c241e08bbc63c63cce39d4d172b3135c6e5289f8/content_delegate.js#L29

**Comment by sjschultze** [comment]
It appears that this is because 

`https://recapextension.org/recap/query_cases/`
has payload
`json={"court":"dcd","casenum":null}`
so response is null

**Comment by sjschultze** [comment]
Problem occurs on both HistDocQry.pl and DktRpt.pl

**Comment by mlissner** [comment]
OK, so this was because we were using the referrer to get the casenum. I have no idea why that was, so I left it in place, and now we have the following code:

```
var url = window.location.href;
// I'm unclear why we use the referrer here. Previously this didn't fall back
// on the current URL, and so it straight-up failed if somebody just GETted the
// docket URL. This seems weird to me that we rely on the referrer (the previous
// URL and forgo the current one.
var pacer_case_id = PACER.getCaseNumberFromUrl(document.referrer) ||
        PACER.getCaseNumberFromUrl(url);
```

That'll try the referrer first, and failing that, it'll try the URL. I'm almost ready to yank the referrer code, but I'm keeping it until I figure out why it exists or conclude it's just weird. Anyway, this is fixed!
