### ISSUE TITLE
Example of case docket (and possibly documents) not updating properly for civil CAND (example from Pacer Case #231846) 

### ISSUE THREAD

**Issue by bkuhn** [freelawproject/recap#162]
I noticed this on one specific case, which I mention here.  I think there is definitely something odd because this case of high interest to the set of people likely using RECAP, and the information reported by the plugin seems to indicate items have been uploaded to archive.org that are not there.  (I tested this myself and confirmed the problem, as explained below)

For example, visiting this URL while logged into pacer:
https://ecf.cand.uscourts.gov/cgi-bin/DktRpt.pl?231846

I see  from the plugin:
   Get this docket as of 05/11/16 for free from RECAP.
   Note that archived dockets may be out of date.

Yet, the docket shown at:
http://ia902304.us.archive.org/0/items/gov.uscourts.cand.231846/gov.uscourts.cand.231846.docket.html

has no items in it beyond 2015-09-17.

I know that I and others have looked at this docket in Pacer many times since then with the plugin enabled, and additionally the date that the plugin now shows is today's date, yet the docket is not updating.

Also, there are many documents missing in this case that surely many (including myself) with the plugin have downloaded.

For example, I downloaded this one:
gov.uscourts.cand.231846.1858.0.pdf

But it is not shown in the archive of documents here:
http://ia902304.us.archive.org/0/items/gov.uscourts.cand.231846/

I don't know if there is something odd about this specific case, or if it points to a widespread problem.

**Comment by mlissner** [comment]
@bkuhn, this is an _excellent_ bug report, thanks so much for the great level of detail. 

So, looking at this docket, I can be pretty sure I know the problem: It's just too big. If you've been using RECAP for a while, you probably have noticed that from time to time there is a major lag between when you upload an item and when that item becomes available. This is due to what we call "mega dockets", and unfortunately, they can really break our current system. Sadly, we have code in place that blocks these mega dockets from clogging things up. 

That's the bad news. The good news is we're working on a new and more powerful system, and I expect it'll have less trouble of this kind.

**Comment by johnhawkinson** [comment]
This case (Oracle v. Google) is a sufficiently big deal that it would be great to be able to ge tthe documents, unlike some boring megadockets nobody gives a hang about.
Is there any chance of at least making it so that the documents will upload, even if the docket info can't be processed? That would be a help.

One does kind of wonder what kind of n^5 code is in there such that 1,000 dockets breaks it, though. Is it a function of the size of the docket entire, or just the size of the chunk that is uploaded? I'd be willing to put some effort into it (since I care at least a little about this case...)

**Comment by mlissner** [comment]
The problem as I understand it is in the XML rendering of the docket entire, which is something that we do before pushing the docket to IA. In these mega dockets, this process can take _days_. I think that's really weird too, but I haven't looked at it deeply. @harlanyu or @sjschultze, correct me if I'm wrong about what part of the pipeline this is that's causing issues.

I don't think there's any particularly easy solution for it, but if you're interested in taking a look, that'd be very welcome.

**Comment by johnhawkinson** [comment]
So, again, the direct question: Can we trivially modify the megadocker-blocker to permit the PDFs to upload to IA while still suppressing the expensive XML processing? (Where is that megadocket-blocking code?)

**Comment by mlissner** [comment]
The mega blocking is done by setting a value in the DB to say that the item is really big and stop uploading it. We do this periodically for big dockets because if we don't they totally clog things down. 

The fix is probably to remove that value for this docket (and all dockets, ideally), and to put in some code that automatically detects mega dockets and then only pushes their PDFs, blocking the XML from rendering.

**Comment by johnhawkinson** [comment]
Err, before we reach that, can't we adjust the code that handles that flag to allow the PDFs upload while still blocking the XML processing? Anyhow, what's the db flag called, so I can find the relevant code?

**Comment by mlissner** [comment]
Sorry @johnhawkinson, didn't see your response here. The query we use once we identify one of these mega dockets is something like:

```
insert into uploads_bucketlock values ('','nysb','171257','1','bigdoc','0','0',NOW());
```

Is that enough to run with?
