### ISSUE TITLE
Talk about RECAP on the Donate page

### ISSUE THREAD

**Issue by anseljh** [freelawproject/recap#188]
There's a big lovely Donate button in the RECAP extension. If you click it, you go to [this page on CourtListener.com](https://www.courtlistener.com/donate/?referrer=recap-chrome-options), which talks about CourtListener—but _not_ about RECAP. It should talk about RECAP, _especially_ if the referrer is the RECAP extension, which we know (`?referrer=recap-chrome-options`).

My suggestion is, if the referrer is RECAP, then there should be some large, conspicuous text saying something like "RECAP is a project of Free Law Project. Please support Free Law Project!"

**Comment by anseljh** [comment]
The fact this page is on CourtListener.com is another point of confusion. As a user, I click a button in the RECAP extension, and end up on CourtListener.com reading about Free Law Project and CourtListener, but not RECAP. Huh?

A few more options:

* Move the page to free.law
* Point the extension to [the Donate page that's already on free.law](https://free.law/donate/)
* Make a new donation landing page on free.law just for RECAP users (I'm currently favoring this option)

**Comment by mlissner** [comment]
This has bugged me too, thanks for filing it. I took the simple route and just sent RECAP folks over to the existing page. It's got RECAP as the first bullet point. 

The reason we shuttle people over to CourtListener to actually make payments is because free.law is a static site, so doing payments there is hard.
