### ISSUE TITLE
Only have one notifications option in RECAP, not two.

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#193]
This fits in with #185, because it'll allow us to have a simpler dialog box. Right now it has two options:

1. Notify me on login
2. Notify me on upload

People like notifications or they don't. Let's just have one notification box, eh? Once that's done, it'll be easier to add a choice for file names, and I think we'll be off to the races.

**Comment by johnhawkinson** [comment]
> People like notifications or they don't.

I am...actually not sure that's true.

As a classic FF user, I traditionally had notifications on, and my OS default made them audible as well as an ephemeral notice window in a corner of my screen. In relatively recent months, I found myself doing more PACER work than in the past, and it got to the point where I disabled the audio (esp. because it would occur seemingly multiple times for the "login" notice).

I was kind of looking forward to experimenting with the recap-chrome extension's more fine-grained options. I think I'd like a notice, maybe audible, with the upload, but not with "login," whatever that means.

But I'm not sure. (And I haven't had a chance to experiment with that in the new extension since it took all my discretionary time to try to get baseline functionality working, cf. #182).

> Once that's done, it'll be easier to add a choice for file names

Seems like taking away features should not be on the priority list ahead of feature parity in the days before the public release that is time-sensitive driven by external deadlines.

**Comment by mlissner** [comment]
This code is already in place, I'm afraid, and about to land. 

On this one, I'm making an executive decision to simplify, especially since it's not a big difference to get a few more notifications when RECAP activates — plus, this brings us closer to old FF parity. It already feels nicer to me having fewer options.
