### ISSUE TITLE
browser_style unspecified in browser_action options

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#203]
I get:
```
1510752315611	addons.webextension.info@recapthelaw.org	WARN	Please specify whether you want browser_style or not in your browser_action options.
```

at Firefox startup on stdout (or in the JS console with `--jsconsole`).
Assuming it's not just me, fix this.

cf. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action

Name | Type | Description
-- | -- | --
browser_style | Boolean | New in Firefox 48      Optional, defaulting to false.      Use this to include a stylesheet in your popup that will make it  look consistent with the browser's UI and with other extensions that use  the browser_style property. Although this key defaults to false, it's recommended that you include it and set it to true.

I guess this goes in `manifest.json`

**Comment by mlissner** [comment]
Yeah, this should be easy. Just need to make sure it doesn't upset Chrome or Opera.

**Comment by mlissner** [comment]
Well, there's really no winning here unless we go the route of having different manifest files for Chrome and Firefox. If we add this key to the `browser_action` section of the manifest, Chrome complains. If we don't, Firefox complains. Neither one has changed functionality aside from the complaining.

I'm just going to leave this alone and let Firefox continue complaining since the defaults are suiting us fine.

(One other thing, if we do get back to this bug someday: If we add the `browser_style` key to the `browser_action` section, we also should add it to the `options_ui` section, where it has largely the same functionality, though that one defaults to `true`.)

**Comment by mlissner** [comment]
Note that if we reopen #181 (make a build script for the extension), we should reopen this too.
