### ISSUE TITLE
Documents downloaded with show_doc links lack a pacer_case_id value

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#205]
Even though the main file knows the case ID, its attachment here seems to have forgotten it.
![downloads](https://user-images.githubusercontent.com/8204476/32849247-78ac4d56-c9e3-11e7-94c0-4e8bf47ac9f4.png)

**Comment by mlissner** [comment]
What do you mean the main file? The third item in the screenshot?

**Comment by PlainSite** [comment]
Yes, Document 1 here would be the main file, and Document 1-1 is an attachment.

**Comment by mlissner** [comment]
Here's what @PlainSite said about this ticket over in #206:

> FYI, regarding the unknown-case-id (issue #205), I got this by going to https://ecf.pawd.uscourts.gov/cgi-bin/show_doc.pl?caseid=239143&de_seq_num=&dm_id=&doc_num=1. So maybe this is the link scheme that is no longer supported, even though the case ID is right in the link?

> Even though PACER may not be displaying them anymore, there are still probably tens of thousands of these links in the PlainSite database that would be very expensive to update.

**Comment by mlissner** [comment]
We removed support for show_doc links after discussing it in #171. I think since PACER doesn't support them anymore, it shouldn't be that hard to update the links you have in your DB. If we can find more places that are affected by this outside of PlainSite, I'd consider reverting, but if I can help it, I don't want to support a legacy-style link forever that PACER itself has stopped using.

**Comment by johnhawkinson** [comment]
So this is the big mystery -- @plainsite where are you getting `show_doc` links?

**Comment by PlainSite** [comment]
The PlainSite MySQL database stores the links from previous RECAP version scrapes. Back in the day, there were a lot of them.

**Comment by mlissner** [comment]
Should be fairly easy to upgrade these, right? Seems inevitable since PACER has moved on? You've got the doc ID values, I assume?

**Comment by PlainSite** [comment]
Not sure how that would be possible... I'd have to purchase the history for thousands of dockets, unless you're saying those are stored on your side somewhere for documents not yet in RECAP. There are no doc1 values for these because at the time that's not what was transmitted.

**Comment by mlissner** [comment]
Oh, I gotcha. Are these items you got outside of RECAP? If not, is it easy to show me an example Internet Archive XML file that would generate these kinds of links?

**Comment by PlainSite** [comment]
For example, http://ia800909.us.archive.org/9/items/gov.uscourts.cacd.560453/gov.uscourts.cacd.560453.docket.xml, last updated August 8, 2013.

![xml](https://user-images.githubusercontent.com/8204476/32906655-6af77df0-cab2-11e7-913f-d6abca182821.png)

Note "pacer_de_seq_num" and "pacer_dm_id" XML tags. "caseid" is implicit as it is defined by "pacer_case_num" for the entire document.

Additionally, there may be others I sourced from Aaron Swartz's original data dump. But there's still clearly some of these links in the RECAP archive.

**Comment by mlissner** [comment]
OK, gotcha. I wanted to figure out why this isn't affecting CourtListener, so I dug into how we're solving this. Our solution is that when we don't have a pacer_doc_id value (that can be used to make a `doc1` URL), and we want to make a "Buy on PACER" button, we just use the pacer_case_id value and let the user figure it out. For example, on this page: 

https://www.courtlistener.com/docket/4149811/credit-acceptance-corporation-v-drivetime-automotive-group-inc/

All of the "Buy on PACER" links go to:

https://ecf.cacd.uscourts.gov/cgi-bin/DktRpt.pl?556022

This is certainly worse than using the show docs links as you are, but we didn't store the de_seq_num values when we parsed the Internet Archive XML, and...this was how it was done since before I got here. 

So, that is how we solved this...by one definition of "solved." 

Given that PACER has stopped using these URLs, another solution is to scrape PACER for the doc1 URL of each URL, and then upgrade them. It should be fairly easy to do, though PACER won't love you for making X million requests. If you wanted to do this, you'd load the HTML for one of the show_docs links, which will show a receipt page. On that page, the form element for the "View Document" button has the doc1 ID in an onclick attribute. So..that's another possible solution. I think if I had the de_seq_num values from IA, this is the solution I'd go for myself.

Or we could figure out the show_docs support in the extension again, and see if it's working. I'm just hesitant to do that because no matter what I do every change to the extension seems to add more bugs....extension dev (though in its golden age), is not a happy place to work.

**Comment by johnhawkinson** [comment]
Living in fear of features adding bugs is no way to live.

It's easy to hope that that any instability associated with `show_doc` support would be confined to that feature, and not affect the rest.

Also, this could be a good time to work on tests.

**Comment by PlainSite** [comment]
Seems much easier to do this (forgive my untested PHP here):

$caseid = preg_match('/(?:caseid=)(/d+)(?:&)/', $url, $match);
$caseid = $match[0];

Now you have the case ID.

As to the above (https://github.com/freelawproject/recap/issues/205#issuecomment-345008341) pseudo-solution: it's easier, but it also costs users more money.

**Comment by mlissner** [comment]
The regular expression isn't the hard part. Extensions are just a nasty place.

**Comment by PlainSite** [comment]
So actually this is happening with doc1 links as well. Oddly, it only happens to attachments (both with doc1 links and legacy caseid links). Suggests you have a bug somewhere.

**Comment by mlissner** [comment]
@PlainSite notwithstanding fixes we need here to the extension, you might want to look at #214. It provides a possible way forward that doesn't require the show_doc links you're using currently. Pretty nice find.

**Comment by johnhawkinson** [comment]
My `goDLS` branch has support for `&caseid=` parsing in URLs. See https://github.com/johnhawkinson/recap-chrome/commit/afedc05318d748d8b8a2143cc129f8de3d96780a.

**Comment by mlissner** [comment]
Echoing what @johnhawkinson said above, I think this will be fixed (I'm hopeful anyway) when freelawproject/recap-chrome#34 is merged and deployed. (Mostly just commenting so the bug and the PR are linked.)

**Comment by mlissner** [comment]
This appears to be fixed.

**Comment by mlissner** [comment]
Nope, not yet fixed. I double checked using this URL:

https://ecf.cacd.uscourts.gov/cgi-bin/show_doc.pl?caseid=534889&de_seq_num=&dm_id=&doc_num=88

The good news is, we're capturing the case number now, but since it's not a doc1 URL, we're ignoring it for upload, and what's more, we're not currently getting the doc1 value from the "View Document" button (which is necessary, since it's missing from the URL itself).

Those are probably the two missing pieces for this to be fixed properly.

**Comment by mlissner** [comment]
OK, I think this should be better now. @PlainSite, if you're able (and willing), I'd love to have you run a beta version of the extension since this mostly affects your website. If you're willing, let me know and I'll get you a release you can use (or you can pull from source, if you're so brave).

I know you don't want to support RECAP anymore, but this felt like the right thing to do to get your biggest (non-philosophical issue) taken care of. I hope this improves your feelings about the new RECAP system, if only marginally.
