### ISSUE TITLE
Add a variety of optional enhancements to PACER

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#207]
This is a follow on from #191.

The idea here is to add another checkbox to the options that just says something like:

 - [ ] Optimize PACER (learn more)

By default it could be off, but when enabled, it'd make little changes that make PACER more palatable:

1. Uncheck Parties and Counsel from the docket report page.
1. Check "Include headers" on the docket report page.
1. Check "List of member cases" on the docket report page.

What else? I imagine there's a lot more we could do here.

**Comment by johnhawkinson** [comment]
As expressed in #191, I don't think this is a great way to go.

First and foremost, it's not self-documenting. An option like "Uncheck Parties and Counsel box" is fairly clear and unambiguous. It doesn't need a "learn more" link and the extra baggage that brings. It's narrow and surgical. But "Optimize PACER" is nearly meaningless, as you've recognized with the "learn more" link. That's an extra click to understand, an extra click most users will never try. Single-page UIs are generally better than multi-page UIs unless there is so much information it doesn't comfortably fit (we are nowhere close).

Secondly, a broad option is future-ambiguous, and that's bad. If I check it now, the definition of "Optimize PACER" may change in the future. That's kind of like an opt-out system without clear notice of the opt-out choice, and those systems are generally disfavored by users but liked by system developers (because fewer people will make conscious choices so they get higher adoption rates).

Thirdly, I don't think it's apparent that user desires all track each other on these. I mean, you can say, sure, "Who wouldn't want Include headers"? and I think a lot of districts check it by default? I dunno about "List member cases" -- does that add to the page count and result in more $0.10 charges?

Anyhow, just my opinion as a PACER user.

**Comment by mlissner** [comment]
Definitely appreciate it, John. I actually see the future-ambiguity as a feature. I see this feature as an escape valve that people can use to tell us they aren't sticklers.

**Comment by johnhawkinson** [comment]
> _"generally disfavored by users but liked by system developers "_

\:)

**Comment by johnhawkinson** [comment]
> What else? I imagine there's a lot more we could do here.

4. Fill in the last docket number or date thereof in the `date_from` or `document_numbered_from` fields, in order to limit the report to only what is new.

Problems:

(a) What if RECAP had partial information, e.g. it had docs 101-102, but not 1-100?
(b) Some courts (EDNY, for example) don't display unnumbered documents when you set document_numbered_from. This is irritating and creepy and maybe even a bug?
(c) Even the people who want this probably do not want it all the time. Thereofre there should be a button added to the page to do these functions (and maybe submit the form? Or maybe not.)

**Comment by johnhawkinson** [comment]
Oops, I guess I mentioned the 4(c) button idea in #190.

**Comment by mlissner** [comment]
Eh, I'm not seeing anything here being worth doing. Closing.
