### ISSUE TITLE
Bankruptcy courts might not use onclick attributes on links? 

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#231]
Got a bug report today on Twitter and the guy is having issues with case number 17-13797 in CAEB. Looking into it, it fails because the links in the docket don't have the onclick handler we look for:

```<td>
  <a href="https://ecf.caeb.uscourts.gov/doc1/032026788825" 
    oncontextmenu="this.href=&quot;https://ecf.caeb.uscourts.gov/doc1/032026788825&quot;">281</a> 
  <br>
  <nobr>(2&nbsp;pgs)</nobr>
</td>
```

Could it be bankruptcy courts don't use these onclick handlers?

**Comment by johnhawkinson** [comment]
This is more clearly documented at https://twitter.com/ihatetonyy/status/954162045900894208 from @ihatetonyy and the stack trace (OCRd) is:

```
Uncaught TypeError : cannot read property ' match' of null pacer.js : 260
at Objec t. parseGoDLSFunction ( pace r js:260 )
at ContentDe l egate . f i ndAndstorePacerDoclds (conten_ delegate.js : 51)
at new contentoelega t e (content de)eeate.js:20 )
at content. j s : 15
```

because in https://github.com/freelawproject/recap-chrome/commits/f9852a2dacab02c50a8491586904156975be0c92 we assumed that `link.getAttribute('onclick')` would always return a String, but sometimes it returns null instead.

Anyhow, fixed in freelawproject/recap-chrome#40

> Could it be bankruptcy courts don't use these onclick handlers?

It was never intended that the presence of `onclick` handlers be required. Merely parsed if they are present.
