### ISSUE TITLE
Consider submitting receipt info to the RECAP server

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#245]
Placeholder to consider submitting partial or full information from PACER receipts to RECAP server.

Pros:
* Allows us to know whether document was a free or not, which may be useful statistical information in discussions about PACER pricing policies and maybe in some of the pending PACER fee litigation.
* Allows us to represent how much money RECAP has saved 

Cons:
* Potentially invasive; could allow tracking of individual users if usernames (which are part of the receipt) were submitted.
* If implemented as a separate POST, could have performance impacts (more round trips), even though they are nonblocking.

Of course, if parsed and merely the $ figure is sent, those cons can be mitigated.

Free looks, if/when supported, could complicate the statistical utility of this.
Schema should be designed to include "don't know" as distinct from $0.00.

**Comment by mlissner** [comment]
FWIW, we already get the username info in the docket reports we receive, since they have receipts at the bottom (usually).

**Comment by mlissner** [comment]
I don't think we get much from this, so I don't support doing it. We know if something is a free doc because we get it from the free opinions report every night. If it's not free and somebody buys it, we know how many pages, so that gives us the price. Sometimes we know the page count from the attachment page but don't have the doc, and in that case, we can compute the price from that.

I guess if somebody went to the receipt page without buying the doc and also skipped the attachment page, this would qualify as possibly-useful info, but I think we're doing OK without it and it's not worth making a parser for it, etc.
