### ISSUE TITLE
A Large Docket Not Working

### ISSUE THREAD

**Issue by brianwc** [freelawproject/recap#303]
I don't know if this is related to freelawproject/recap#218 or freelawproject/recap#261 but we only get a partial segment of this docket:
https://www.courtlistener.com/docket/38277337/united-states-v-pacific-gas-and-electric-company/

On the website we show just entries 1213-1280 (with no pagination to let you go back or forward) but we are definitely getting individual documents outside that range as we have the scathing filing from Judge Alsup yesterday, [docket number 1559](https://storage.courtlistener.com/recap/gov.uscourts.cand.276096/gov.uscourts.cand.276096.1559.0.pdf).

Since this is a docket with journalists interested in it, it would be nice for it to perform better.

**Comment by flooie** [comment]
@brianwc 

This looks like a good news bad news (but mostly good news situation).  It looks like we have a duplicate of the case on CL but the one you found is incomplete.  You can find the full docket with pagination (including the portion of the docket on the dupe) here.

[https://www.courtlistener.com/docket/4180753/united-states-v-pacific-gas-and-electric-company/](https://www.courtlistener.com/docket/4180753/united-states-v-pacific-gas-and-electric-company/)

**Comment by flooie** [comment]
@mlissner the duplicate has been inactive for a year and has no PDFs linked to it.  I would think it would be safe to simply delete the mistake.  Would this be appropriate?

**Comment by johnhawkinson** [comment]
Guys, this is a criminal case. Therefore it is subject to the doppelganger docket problem freelawproject/courtlistener#2185, as every single criminal case is. There are at least 2 sub-cases to retrieve any document in a criminal case (_n+1_ where _n_ is the number of defendants), and depending on which you use, some will have some docs and some will have others.

There's something to be said for prioritizing fixing this problem, or maybe adding some mitigation for it since apparently we cannot allocate the resources to fix it properly :(

**Comment by mlissner** [comment]
Yep, closing this as a dup, unfortunately. I honestly don't understand what it will take to fix this, but if we can break that dam, that'll go a long way. Somewhere we need to update our data model to handle this, but I don't understand the PACER data well enough to understand how the model needs to be updated.

Mitigations welcome too (but also over at freelawproject/courtlistener#2185). It is indeed one of our worse bugs.

**Comment by flooie** [comment]
Wait, Can't we just do something like this 

Docket number and court 

https://www.courtlistener.com/api/rest/v3/dockets/?docket_number=3:14-cr-00175&court=cand

and add them as tabs for associated cases if it comes back as > 1

@mlissner @johnhawkinson

**Comment by johnhawkinson** [comment]
So, it turns out I was a little too summary in my review and disposition.
This is even more broken than the usual kind of doppelganger situation, because the CL page Brian cited is associated with a now-invalid `pacer_case_id` in N.D. Cal. I would imagine this might have happened when the case was transferred from Judge Henderson to Judge Alsup, but maybe not. So in any event, there exist:

https://www.courtlistener.com/docket/38277337/united-states-v-pacific-gas-and-electric-company/ that Brian noted, which links that mostly don't work, but kind of if you push them hard enough
https://www.courtlistener.com/docket/4180753/united-states-v-pacific-gas-and-electric-company/ with 9 pages of docket entries for id 276096
https://www.courtlistener.com/docket/4180752/united-states-v-pacific-gas-and-electric-company/ with 8 pages of docket entries for id 276095

Note that this situation where the CL docket id numbers (4180752, 4180753) are adjacent is rare and cannot be relied upon. Whereas the adjacent pacer_case_id numbers (276095, 276096) is the normal situation (but is not always true, e.g. if a new defendant is added after the initial case opening).
