### ISSUE TITLE
Attachment page not uploaded

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#304]
I couldn't figure out why this one doesn't upload: 

https://ecf.flmd.uscourts.gov/doc1/047024143220?caseid=395057

On CL here: 

https://www.courtlistener.com/docket/60650721/141/navy-seal-1-v-austin/

I looked at the logs of the foreground and background page, but nothing obvious came up. Somebody needs to debug. Feels like there's probably a corner case here or if nothing else, an opportunity to log something better.

**Comment by queesamor** [comment]
### Problem
The issue appears to be with the **PACER.isAttachmentMenuPage()** method, specifically here: https://github.com/freelawproject/recap-chrome/blob/32235a719743b2b7c143c605ead05506128b103b/src/pacer.js#L302

This is called from content_delegate.js within the **handleAttachmentMenuPage()** method, and since the return from **PACER.isAttachmentMenuPage()** is false, this method returns without actually handling the attachment menu page, here: https://github.com/freelawproject/recap-chrome/blob/32235a719743b2b7c143c605ead05506128b103b/src/content_delegate.js#L321

Ultimately, at the Pacer page cited by Mike, you will notice that although there are quite a few attachments, there are no buttons _(inputs)_ on the page, whereas **PACER.isAttachmentMenuPage()** is expecting there to be at least one button, the very last input on the page, with a value of "_Download All_". This page, though, simply ends with this note:
> Note: You must view each document individually because the combined PDF would be over the 50 MB size limit.


### Possible Solution
In keeping with the current approach in pacer.js, you could insert this line above line 302:
`let mainContent = document.getElementById("cmecfMainContent");`

and update line 302 _(now 303)_ to something like the following, which would cause the rest of the handling of this (and similar) attachment page(s) to proceed as expected, at least according to my testing in Chrome 98:
`if ((inputs.length && last_input.value === "Download All") || mainContent.lastChild.textContent.match(/view each document individually/)) {`


### Wrapping up
Sorry I haven't set up a local dev environment, forked the repository, applied the above-suggested changes, and submitted a PR. Unfortunately I am not able to proceed with such a thorough assist at this point, but wanted to at least offer the progress of stage 1 troubleshooting to speed things up for your team. 🤗

**Comment by mlissner** [comment]
Excellent analysis. Yes, this looks like the fix we need. We don't have anybody working on RECAP right now, but we can try to include it eventually when we get back to it. Looks like a very easy change for a nice little fix.

**Comment by mlissner** [comment]
@ERosendo, this will be a great first fix for you to use to get familiar with the RECAP extension. I'm putting it on the top of your backlog.

**Comment by mlissner** [comment]
I believe this is fixed via freelawproject/recap-chrome#269
