### ISSUE TITLE
Insert RECAP links and Upload the Case Summary page from Appellate PACER

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/recap#314]
This page only shows the ten most recent entries for the docket and also has the link to the district court case. The extension should insert links if the document is available in the archive and should upload the page to courtlistener. Here's a screenshot of this page:

![image](https://user-images.githubusercontent.com/55959657/205376686-fa37c2dd-3d3f-4a5c-87cc-adf9d1ff4051.png)

@albertisfu this is one of the new pages that the extension will be sending to the API. You can take a look at this page following this link: [20-15019 Case Summary](https://ecf.ca9.uscourts.gov/n/beam/servlet/TransportRoom?servlet=CaseSummary.jsp&caseNum=20-15019&incOrigDkt=Y&incDktEntries=Y)

**Comment by albertisfu** [comment]
Thanks, I did a parse test and seems that this one is a Docket Appellate and can be parsed using the `AppellateDocketReport`

We have already an `upload_type`  `APPELLATE_DOCKET` and the task to process them. 
Unless I'm missing something we should be ready from the backend to accept this page.

**Comment by mlissner** [comment]
Can you check, Alberto, how docket entry numbers are determined for these? And Eduardo, can you tell Alberto what API call the extension will use to check for docket entries to see if they're in RECAP? If you can tell him that, he can make sure that the two parts line up — that the way we parse dockets and the way we check for available docket entries both create the same IDs.

**Comment by ERosendo** [comment]
the current implementation of the extension uses a GET request to the **recap-query** endpoint ( `/api/rest/v3/recap-query/` ) to check for docket entries. it sends the document ID numbers found in PACER as a comma-separated list and also the court abbreviation. Here's an example of this request:

```
curl 'https://www.courtlistener.com/api/rest/v3/recap-query/?pacer_doc_id__in=097012792270%2C097012795545%2C097012795634&docket_entry__docket__court=mied'
```

**Comment by albertisfu** [comment]
Yes, the document_number (docket entry number) is returned from the docket entry row if available if not (like in courts that don't use document numbers e.g: ca11) the document number is filled with the `pacer_doc_id` if it's available otherwise the document_number is `None` https://github.com/freelawproject/juriscraper/blob/main/juriscraper/pacer/appellate_docket.py#L564

Thanks, Eduardo, well if we use the `pacer_doc_id`  to check if a document is available in RECAP we should be good since the `pacer_doc_id` seems to be available in every docket entry that has a document. I checked some examples and there are entries without `pacer_doc_id` but those entries don't have a link to a document.
