### ISSUE TITLE
Appellate: PDF not displayed after purchase

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#323]
When purchasing an appellate doc, it shows that it is uploaded, but the iframe (?) that appears afterwards doesn't let me see the PDF.

This really bad because it means users can't get PDFs from PACER. For attorneys in a rush, this could make them permanently remove the extension, if they figure out what happened! 

Interestingly, I do see the button to download the PDF:

![image](https://user-images.githubusercontent.com/236970/209865632-2f158f84-d2fe-44c1-aaad-c5f4d7d87db5.png)

Clicking the button does work, so that's good at least.

STR:
 - Purchase doc 10 from: https://www.courtlistener.com/docket/8034892/10/nvlsp-v-united-states/

Expected Results:
 - The doc should be shown in the browser or downloaded, depending on the settings of the extension.

Actual Results:
 - The doc is not shown in the browser or downloaded and appears to be invisible.

**Comment by ERosendo** [comment]
I purchased doc 10 from [19-1083](https://www.courtlistener.com/docket/8034892/nvlsp-v-united-states/) using the "Buy On PACER" link and the direct link from PACER (I did this using chrome and firefox ), but I was not able to reproduce this error.

This issue seems to be related to https://github.com/freelawproject/recap/issues/324.

**Comment by mlissner** [comment]
Oops, that should have been doc 8.

**Comment by ERosendo** [comment]
Are you sure? The button to download the file says `13514.97` in the screenshot and the link of entry number **10** from [19-1083](https://www.courtlistener.com/docket/8034892/nvlsp-v-united-states/) was redirecting to doc **97** from [19-1081](https://www.courtlistener.com/docket/8063767/nvlsp-v-united-states/) ( which `pacer_case_id` is 13514) before we merged https://github.com/freelawproject/recap-chrome/pull/298.


Doc 8 from [19-1083](https://www.courtlistener.com/docket/8034892/nvlsp-v-united-states/) is an opinion and we don't upload those docs to RECAP (for now) because the user doesn't get shown the receipt page.

**Comment by mlissner** [comment]
OK, I was wrong, this is because I have Firefox set to "Always Ask" about what I want to do with PDFs. This is what happens when you have that setting on, and it's fine. Closing, sorry for the trouble.
