### ISSUE TITLE
Appellate: Failed PDF upload, "Duplicate key on unique_together constraint" 

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#327]
I went purchased a docket with the dev version of RECAP today (on the main branch), and then clicked one of the items. It led to the attachment page, and I selected and purchased a document, which uploaded here:

https://www.courtlistener.com/api/rest/v3/recap/7398014/?court=cadc&upload_type=3

It reports the error that:

> Duplicate key on unique_together constraint

Not sure why. This could indicate a back end issue or that it was uploaded incorrectly. Eduardo, can you check that the upload looks correct for a doc from this URL:

> https://www.courtlistener.com/docket/66696476/shawn-musgrave-v-mark-warner/

It's the entry from 2022-10-28 that is described as, "STATEMENT OF ISSUES".

If the extension part looks good, then we should pass this to Alberto for a look next.

**Comment by ERosendo** [comment]
I reviewed this issue and found that the extension uploaded the file incorrectly.

The current implementation of the extension should send the `document number` and the `attachment number` when it uploads files from **attachment menu** pages. The extension uses a regex expression to parse these values from the title on the **download confirmation page** (here's the [helper](https://github.com/freelawproject/recap-chrome/blob/2bcb03a9a75ac45cbf9a70a287db15a058546dea/src/appellate/utils.js#L237-L264) that handles the parse operation). This helper method expects a title that looks like the following (if the document belongs to an attachment page):

- **Document: PDF Document (Case: 20-15019, Document: 1-1)**

but in this case, the title on the **download confirmation page** is the following:

- **Document: PDF Document (Case: 22-5252, Document: 01218465987)**

The extension is not sending the `attachment number` because it's not included in the title.  

Here's a screenshot of the **download confirmation page** of a document from docket 22-5252 and also a screenshot of the **download confirmation page** of a document that belongs to an attachment page of a different docket.

 **Document from docket [22-5252](https://www.courtlistener.com/docket/66696476/shawn-musgrave-v-mark-warner/)**  
<img src='https://user-images.githubusercontent.com/55959657/210465011-84ce45d7-9ee2-4140-b9b3-a14a13984da3.png' width=600>

 **Document from docket [19-1083](https://www.courtlistener.com/docket/8034892/nvlsp-v-united-states/)** 
<img src='https://user-images.githubusercontent.com/55959657/210466689-7f19fffd-13de-42aa-98ad-d2349be9c09e.png' width=600>

**Comment by mlissner** [comment]
Nice analysis, thanks. I'll follow up with the courts, but until they fix themselves, I guess we gotta work with what we've got.

**Comment by ERosendo** [comment]
I also noticed that the attachment page shows the `attachment number`. Here's a screenshot of the attachment page for this docket entry

![image](https://user-images.githubusercontent.com/55959657/210467747-656f0007-40ff-44ba-aa1a-2131775ee7d3.png)

We can fix this issue if we pass the `attachment number` from the **attachment page** to the **download confirmation page**. We could use the tab storage to do this or add the attachment number as a query string parameter to the document link ( like ?attNumber=1).
