### ISSUE TITLE
Provide two buttons on RECAP receipt page one to RECAP the doc, the other to download the normal way

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#357]
When people log into PACER, we now detect if the modal pops up warning them about redactions. If it does, we show them notifications about recap.email and how it might be useful to them. 

We should use this same trigger to enable an option that restricts uploads for these users. It could work in a number of ways, but it came up today during our discussion with a [LSC corp](https://www.lsc.gov) that is trialing RECAP. Their concern is violating [a rule](https://www.law.cornell.edu/rules/frcp/rule_5.2) in Social Security cases by uploading something they should not.

A few solutions are possible:

1. It's possible that in SS cases, PDFs already have the notification that the content is sealed. If so, the extension automatically won't upload the doc.
2. I'm kind of assuming that's not the case, so tighter option is that if the user sees the "Redaction popup", then we don't upload PDFs at all. 
3. Another option is to detect the redaction popup. If it's there, then we add a new button on all the document download pages that says, "Download with RECAP Upload" or something like that, so the user chooses each upload or not.
4. This only applies to some case types. We could only show that button when the document is from a social security case, according to the NOS code.

And probably some other options! 

We're waiting to hear from the folks at the LSC whether the warning banner is there, and we can go with option one, above (do nothing, it's already safe), but I'm happy to hear thoughts.

**Comment by johnhawkinson** [comment]
As you know, FRCP 5.2 is my favorite (not).
There is a point where it's important to distinguish between "sealing" and "restricting."
Social Security and immigration cases are not sealed, they are restricted.
Downloading a document restricted per 5.2(c) does indeed lead to the warning about documetns being restricted to case participants and court staff, yes.

>  if the user sees the "Redaction popup", then we don't upload PDFs at all.

I think you are confused? All cases get the redaction pop-up about when you file a document, not just 5.2(c) cases.
But you don't get this at download time, only upload time.
Am I missing something?


> 1. It's possible that in SS cases, PDFs already have the notification that the content is sealed. If so, the extension automatically won't upload the doc.

So....(1) is true except you used the wrong words.

>2. I'm kind of assuming that's not the case, so tighter option is that if the user sees the "Redaction popup", then we don't upload PDFs at all.

(2) False. Also, everyone gets the redaction pop-up, not just 5.2(c) cases.

>  3. Another option is to detect the redaction popup. If it's there, then we add a new button on all the document download pages that says, "Download with RECAP Upload" or something like that, so the user chooses each upload or not.

(3) Err…we already detect the pop-up, right?

> 4. This only applies to some case types. We could only show that button when the document is from a social security case, according to the NOS code.

(4) This is … not great. Not all courts apply the NOS codes the same way (…), and not everybody restricts cases the same way. And some cases that technically fall under 5.2(c) don't really need to be restricted and courts sometimes recognize that, either _sua sponte_ or at the request of the parties, or at the request of media intervenors (hi) or other people. Or even by local rule. For instance, if the ACLU files a class action lawsuit challenging some immigration issue, it'll be NOS 463 so if you only look at the NOS you'll decide it is restricted…but almost everyone agrees that "impact" litigation with significant public interest and that does not concern the private details of individuals doesn't require the 5.2(c) restrictions.

Also, it's not rare that, e.g., an immigration case is filed as NOS 530 (general habeas) when someone else might have filed it as NOS 463. A court clerk may then go and restrict the case, but not change the NOS. 

The result is the NOS code is not a reliable indicator of restricted-ness.

I also have a vague unsubstantiated memory that more than the pure NOS code is used, like cause code? Not sure on this one.




> 

>

**Comment by mlissner** [comment]
> As you know, FRCP 5.2 is my favorite (not). There is a point where it's important to distinguish between "sealing" and "restricting." Social Security and immigration cases are not sealed, they are restricted. Downloading a document restricted per 5.2(c) does indeed lead to the warning about documetns being restricted to case participants and court staff, yes.

OK, great, so perhaps this is all moot, at least for SS cases, but I'll press on in case there's more to cover.

> I think you are confused? All cases get the redaction pop-up about when you file a document, not just 5.2(c) cases. But you don't get this at download time, only upload time. Am I missing something?

The popup I'm referring to is the one that you see when you log in. We can use that to detect somebody that's not just a boring PACER account. It'll catch people it shouldn't, but it's reliable. 

 
> > 1. It's possible that in SS cases, PDFs already have the notification that the content is sealed. If so, the extension automatically won't upload the doc.
> 
> So....(1) is true except you used the wrong words.

:+1:  


> > 3. Another option is to detect the redaction popup. If it's there, then we add a new button on all the document download pages that says, "Download with RECAP Upload" or something like that, so the user chooses each upload or not.
> 
> (3) Err…we already detect the pop-up, right?

So now that we're talking about the same thing, I hope? Does this idea of adding an extra button to every PDF purchase make more sense? I kind of like this idea as a fairly seamless way of de-risking RECAP for lawyers. 


> > 4. This only applies to some case types. We could only show that button when the document is from a social security case, according to the NOS code.
> 
> (4) This is …not great [NOS is a bad indicator of a case being restricted]

Yeah, I agree, but the thought was that if you have an account that gets the *You must redact* popup on login, then being overly careful might be smart.


> Also, it's not rare that, e.g., an immigration case is filed as NOS 530 (general habeas) when someone else might have filed it as NOS 463. A court clerk may then go and restrict the case, but not change the NOS.

Yeah, we'd miss that, but I guess it'd have the *Restricted Document* banner before download, which we already catch, so that'd be OK too.

> I also have a vague unsubstantiated memory...

Yeah, I tried to get at this in our call today: Is the rule subjective or objective. It seems subjective, which means being overly careful is the correct approach. Luckily, we already catch that banner, so I guess we're in pretty good shape, but I still like option 3 above as belt and suspenders.

**Comment by johnhawkinson** [comment]
> OK, great, so perhaps this is all moot, at least for SS cases, but I'll press on in case there's more to cover.

I'm not sure how Social Security cases are distinguishable from immigration cases in the eyes of the rule, so I'm a little confused, but I agree you're right to be a little more concerned. (Obviously they are distinguishable in that your client is concerned with one and not the other.)


> > I think you are confused? All cases get the redaction pop-up about when you file a document, not just 5.2(c) cases. 

Sorry, I misspoke a little there. The redaction warning at time of filing is not a pop-up. (And honestly it's pretty terrible, it is like 3 or 6 navigation screens after the point at which you upload the PDF but before you submit the entry, so yikes? So much for "instructions at the point of use.") screenshot:

<img width="585" alt="Screen Shot 2023-11-07 at 06 07 09" src="https://github.com/freelawproject/recap/assets/1270718/62846822-3492-482f-b98c-efd1b1449181">


> Does this idea of adding an extra button to every PDF purchase make more sense? I kind of like this idea as a fairly seamless way of de-risking RECAP for lawyers.

You're suggesting something like altering receipt pages to have a second button, notionally like this?:

<img width="925" alt="Screen Shot 2023-11-07 at 06 13 19" src="https://github.com/freelawproject/recap/assets/1270718/3e3b840a-daab-4dc9-b92d-b1ab532546fc">


(I'm not trying to offer an opinion on the text or the ordering or the design or whether there should be more emphasis on one button than the other or any of that stuff.)

This is hard for me to think about because of the inherent bias in favor of the familiar. But I do think there's a lot to be said for what you describe. I know that I am often annoyed when I want to Not Upload something to RECAP (for whatever reason) and I have to go and disable the extension (or frob the "Enable uploads" toggle) and often forget to turn it back on...

>> > (4) This is …not great [NOS is a bad indicator of a case being restricted]
> 
> Yeah, I agree, but the thought was that if you have an account that gets the _You must redact_ popup on login, then being overly careful might be smart.

It's also the case that the Court can err in the other direction. That is, a case might not be restricted in CM/ECF, but it should have been, and if so the parties ought to know that and should not be publicizing the documents, even if John Q. Public could reasonably download them via RECAP and lead to their publication. An attorney uploading such a document wouldn't be violating the rule, per se,  but then again, they also wouldn't be violating the rule if they uploaded a properly restricted document. (The rule governs what CM/ECF does, it doesn't govern the outside actions of parties. Indeed, it's perfectly reasonable for an attorney to publicly post an FRCP 5.2-restricted document on their website, and they often do for cases they think are interesting or want to get press about (see "impact litigation," above.) But a judge would take a dim view of an attorney publicizing something that they obviously shouldn't by accident through a technical error resulting from use of the RECAP extension, I suspect.


> Yeah, I tried to get at this in our call today: Is the rule subjective or objective. It seems subjective, which means being overly careful is the correct approach. Luckily, we already catch that banner, so I guess we're in pretty good shape, but I still like option 3 above as belt and suspenders.

I…don't think those are quite the right terms to use.

If your question is, "Does CM/ECF's configuration for a particular document or case govern whether Rule 5.2(c) attaches?" then the answer is technically "Yes, because Rule 5.2(c) is a rule limiting Clerks, i.e. a rule limiting CM/ECF, it is not a rule binding on attorneys." But the spirit of the rule is that attorneys should not be publicizing those documents that the court has restricted without at least thinking about it, and generally that makes sense and attorneys want to do that.


p.p.s: Don't forget FRAP 25(a)(5).

**Comment by mlissner** [comment]
Thanks. You've pointed out a bunch of subtleties in how and what rules apply (the appellate one looks _impossible_ to do automatically).

I think this is plenty to convince me that we should do double-button approach you mocked out (or something similar). Basically, if we detect you might have filing rights or special access rights (by looking for the redaction modal when you log in), then we provide you with two buttons on every receipt page: "RECAP this Doc" and "Buy without Sharing" — or something like that.

(I like the idea of verbing "RECAP" in the button.)

To be very clear, this is the modal I think we should use to trigger this (or, perhaps, maybe we just always show two buttons for everybody):

![image](https://github.com/freelawproject/recap/assets/236970/0fec2654-5e16-4371-8c1d-e4e540df39ec)

**Comment by mlissner** [comment]
One other thought: It's nice that if we do this, we can leave the existing button mostly or entirely alone. Once every few years RECAP breaks downloading, so it'd be nice for folks not to have to uninstall when/if that happens.

**Comment by johnhawkinson** [comment]
> One other thought: It's nice that if we do this, we can leave the existing button mostly or entirely alone. Once every few years RECAP breaks downloading, so it'd be nice for folks not to have to uninstall when/if that happens.

I'm not sure exactly what this means, but I think it would be a mistake to exclude UI choices that involve modification to the existing button. (But "entirely alone" is not "mostly alone")

But I think that partly because I think modifying the existing button is going to be pretty robust — if the modification fails in the common ways in which these sorts of things fail, the button will still exist and still work. Especially if the modification is just to add some additional words or positional styling.

Not sure how our style guide feels about verb-ing our mark. It sounds peculiar to my mind, but that's how words work.

**Comment by mlissner** [comment]
People have been verb-ing RECAP for a while on the Twitters. I'm for it, where it makes sense.
